### ISSUE TITLE
Unable to compile with openfoam 2306 and ubuntu 22.04

### ISSUE THREAD

**Issue by zonexo** [solids4foam/solids4foam#127]
Hi,

As mentioned above. I have tried the #60 fix:

[openfoam/2112](https://github.com/solids4foam/solids4foam/pull/60)

but it doesn't work. My steps are:

1. git clone --branch v2.0 https://github.com/solids4foam/solids4foam.git
2. cd solids4foam
3. git fetch origin pull/60/head:development
4. git checkout development
5. ./Allwmake -j 2>&1 | tee log.Allwmake

I have attached the log file. As a side note, I also tried other clusters like RHEL 8.4 (Ootpa) with OF 2206/2312 but failed too

[Allwmake.log](https://github.com/solids4foam/solids4foam/files/15032931/Allwmake.log)

**Comment by zonexo** [comment]
Sorry, here's the log.Allwmake

**Comment by zonexo** [comment]
Sorry, here's the log.Allwmake

[log.Allwmake.txt](https://github.com/solids4foam/solids4foam/files/15033018/log.Allwmake.txt)

**Comment by philipcardiff** [comment]
Can you try the latest `development` branch of solids4foam, rather than the `pull/60/head:development` version? e.g.
```
git clone --branch development https://github.com/solids4foam/solids4foam.git
cd solids4foam
./Allwmake -j 2>&1 | tee log.Allwmake
```

This should resolve the errors related to
```
error: ‘class Foam::dynamicFvMesh’ has no member named ‘solverPerformanceDict’
  181 |         const_cast<dictionary&>(mesh().solverPerformanceDict()).clear();
```

**Comment by zonexo** [comment]
Yes, it's working now. Thanks!

**Comment by zonexo** [comment]
Hi sorry to reopen this case. I realised that I made a mistake and I had compiled on 2312 instead of 2306. And now I'm having problems with compiling on 2306. I have attached the error log. Sorry for the inconvenience.
[Uploading log.Allwmake.txt…]()

**Comment by philipcardiff** [comment]
No problem. Can you re-upload your log file? The log file in your latest message seems to be a link to this issue.

**Comment by zonexo** [comment]
Hi, here's the log. Thanks!
[log.Allwmake.txt](https://github.com/solids4foam/solids4foam/files/15150295/log.Allwmake.txt)

**Comment by philipcardiff** [comment]
Can you check you are using the latest `development` branch? The first error refers to code, which no longer exists on the `development` branch, i.e. line 181 in `solidModels/nonLinGeomTotalLagSolid/nonLinGeomTotalLagSolid.C`:
```
solidModels/nonLinGeomTotalLagSolid/nonLinGeomTotalLagSolid.C: In member function ‘virtual bool Foam::solidModels::nonLinGeomTotalLagSolid::evolve()’:
solidModels/nonLinGeomTotalLagSolid/nonLinGeomTotalLagSolid.C:181:40: error: ‘class Foam::dynamicFvMesh’ has no member named ‘solverPerformanceDict’
  181 |         const_cast<dictionary&>(mesh().solverPerformanceDict()).clear();
```

**Comment by zonexo** [comment]
Hi, I tried again and it's working. I may have used the wrong command to pull the code. Thanks again for the help.

**Comment by philipcardiff** [comment]
I am glad that the compilation is working. I will close this issue.

For the errors related to `Alltest`, I suggest you examine the log files from these cases. You can check on the forum or other issues for a resolution. If you cannot resolve the issue, you can open an issue focussed on the specific problem.

**Comment by zonexo** [comment]
ok sure, thanks!
