### PR TITLE
updates to compile with OpenFOAM-v2306

### PR DESCRIPTION
**Pull request by olesenm**

### CODE REVIEW

**Comment by pipedream** [comment]
This works on Debian 12 bookworm and gcc 12.2.0 and openfoam-v2306
```
git fetch origin pull/60/head:development
git checkout development
...
Summary statistics
    Number of cases where a run was attempted: 48
    Number of cases where the solver failed: 0
    Number of cases where another command failed: 0

All tests passed: enjoy solids4foam.
```
Without this pull request it failed with:
```
physicsModel/physicsModel.C: In static member function ‘static Foam::autoPtr<Foam::physicsModel> Foam::physicsModel::New(Foam::Time&, const Foam::word&)’:
physicsModel/physicsModel.C:115:5: error: ‘physicsModelConstructorTable’ is not a class, namespace, or enumeration
  115 |     physicsModelConstructorTable::iterator cstrIter =
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
physicsModel/physicsModel.C:118:9: error: ‘cstrIter’ was not declared in this scope; did you mean ‘strstr’?
  118 |     if (cstrIter == physicsModelConstructorTablePtr_->end())
      |         ^~~~~~~~
      |         strstr
physicsModel/physicsModel.C:130:34: error: ‘cstrIter’ was not declared in this scope; did you mean ‘strstr’?
  130 |     return autoPtr<physicsModel>(cstrIter()(runTime, region));
      |                                  ^~~~~~~~
      |                                  strstr
make: *** [/home/jan/0_no_backup_overwrite/OpenFOAM-v2306/wmake/rules/General/transform:38: Make/linux64GccDPInt32Opt/physicsModel/physicsModel.o] Error 1
```

**Comment by philipcardiff** [comment]
Hi @olesenm, this is great. Thank you.

I will go through the changes (and new flags) and then will likely merge this to a new nextRelease branch.

In any case, others can immediately use this.

**Comment by philipcardiff** [comment]
Ah, I see that your changes allow for older versions, too; in that case, this can probably be directly merged to the `development` branch, although a new release is due in any case.

Let me perform some checks.

**Comment by philipcardiff** [comment]
FYI, @ztukovic. I will merge this once I have finished performing checks. After that, we can mark it as a new release (e.g. v2.1).

**Comment by ztukovic** [comment]
@philipcardiff, I have managed to fix backward scheme across different OF versions. Problem is that it is necessary to modify  GeometricField<Type, PatchField, GeoMesh>::storeOldTimes() function for foam-extend and foundation version. v2012 is ok. Also I will introduce into solids4foam backwardDdt scheme with necessary correction.

**Comment by philipcardiff** [comment]
> @philipcardiff, I have managed to fix backward scheme across different OF versions. Problem is that it is necessary to modify GeometricField<Type, PatchField, GeoMesh>::storeOldTimes() function for foam-extend and foundation version. v2012 is ok. Also I will introduce into solids4foam backwardDdt scheme with necessary correction.

Glad to hear it. Ah, that's a pain. OK, we can place the fix in `optionalFixes` and explain in the documentation that this fix is required to achieve optimal performance with Robin coupling. Feel free to create a pull request for the changes or send me the files.

**Comment by philipcardiff** [comment]
@olesenm , I found a fix for using the new centralised `etc/wmake-options` with foam-extend; see bacbea696565a43a774c8011c454ebec624f127a.

The problem is that foam-extend seems to run make from the Make directory; the hacked solution is to check for etc/wmake-options in two locations, i.e.
```
sinclude $(SOLIDS4FOAM_ROOT)/etc/wmake-options
sinclude $(SOLIDS4FOAM_ROOT)/../etc/wmake-options
```
where `sinclude` means that neither give an error. It is a hack because potentially `../etc/wmake-options` unintentionally exists in the OpenFOAM.com/OpenFOAM.org cases (above the solids4foam directory). But I think it is OK. An alternative is to check the existence of each directory but this will get quite wordy in the make file.

**Comment by philipcardiff** [comment]
Thanks again, Mark!
